// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentsScores.Repository.Data;

#nullable disable

namespace StudentsScores.Repository.Data.Migrations
{
    [DbContext(typeof(StoreContext))]
    [Migration("20240204210214_AddingStudentNameInScoreEntity")]
    partial class AddingStudentNameInScoreEntity
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("StudentsScores.core.Entities.English", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("English");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Value = "one"
                        },
                        new
                        {
                            Id = 2,
                            Value = "two"
                        },
                        new
                        {
                            Id = 3,
                            Value = "three"
                        },
                        new
                        {
                            Id = 4,
                            Value = "four"
                        },
                        new
                        {
                            Id = 5,
                            Value = "five"
                        },
                        new
                        {
                            Id = 6,
                            Value = "six"
                        });
                });

            modelBuilder.Entity("StudentsScores.core.Entities.Maths", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Maths");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Value = "A"
                        },
                        new
                        {
                            Id = 2,
                            Value = "B"
                        },
                        new
                        {
                            Id = 3,
                            Value = "C"
                        },
                        new
                        {
                            Id = 4,
                            Value = "D"
                        },
                        new
                        {
                            Id = 5,
                            Value = "E"
                        },
                        new
                        {
                            Id = 6,
                            Value = "F"
                        });
                });

            modelBuilder.Entity("StudentsScores.core.Entities.Science", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Science");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Value = "Excellent"
                        },
                        new
                        {
                            Id = 2,
                            Value = "Good"
                        },
                        new
                        {
                            Id = 3,
                            Value = "Average"
                        },
                        new
                        {
                            Id = 4,
                            Value = "Poor"
                        },
                        new
                        {
                            Id = 5,
                            Value = "VeryPoor"
                        });
                });

            modelBuilder.Entity("StudentsScores.core.Entities.ScoreSubject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("LearningObjective")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Score")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.ToTable("Scores");
                });

            modelBuilder.Entity("StudentsScores.core.Entities.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("StudentsScores.core.Entities.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Subjects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Value = "English"
                        },
                        new
                        {
                            Id = 2,
                            Value = "Maths"
                        },
                        new
                        {
                            Id = 3,
                            Value = "Science"
                        });
                });

            modelBuilder.Entity("StudentsScores.core.Entities.ScoreSubject", b =>
                {
                    b.HasOne("StudentsScores.core.Entities.Student", null)
                        .WithMany("Scores")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StudentsScores.core.Entities.Student", b =>
                {
                    b.HasOne("StudentsScores.core.Entities.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("StudentsScores.core.Entities.Student", b =>
                {
                    b.Navigation("Scores");
                });
#pragma warning restore 612, 618
        }
    }
}
